version: "3.8"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: shilajit-frontend:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shilajit-frontend.rule=Host(`shilajit.apasya.in`)"
      - "traefik.http.routers.shilajit-frontend.entrypoints=web,websecure"
      - "traefik.http.routers.shilajit-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.shilajit-frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: shilajit-backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "5000"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shilajit-backend.rule=Host(`api.shilajit.apasya.in`)"
      - "traefik.http.routers.shilajit-backend.entrypoints=web,websecure"
      - "traefik.http.routers.shilajit-backend.tls.certresolver=myresolver"
      - "traefik.http.services.shilajit-backend.loadbalancer.server.port=5000"

networks:
  traefik:
    external: true
